/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpgRouteImport } from './routes/opg'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSistemSekolahRouteImport } from './routes/_authenticated/sistem/sekolah'
import { Route as AuthenticatedSistemPenggunaRouteImport } from './routes/_authenticated/sistem/pengguna'
import { Route as AuthenticatedSistemPengaturanRouteImport } from './routes/_authenticated/sistem/pengaturan'
import { Route as AuthenticatedSistemAuditRouteImport } from './routes/_authenticated/sistem/audit'
import { Route as AuthenticatedKeuanganTagihanRouteImport } from './routes/_authenticated/keuangan/tagihan'
import { Route as AuthenticatedKeuanganPembayaranRouteImport } from './routes/_authenticated/keuangan/pembayaran'
import { Route as AuthenticatedKeuanganKasBankRouteImport } from './routes/_authenticated/keuangan/kas-bank'
import { Route as AuthenticatedKeuanganCekPeriodeRouteImport } from './routes/_authenticated/keuangan/cek-periode'
import { Route as AuthenticatedAkuntansiLaporanRouteImport } from './routes/_authenticated/akuntansi/laporan'
import { Route as AuthenticatedAkuntansiJurnalRouteImport } from './routes/_authenticated/akuntansi/jurnal'
import { Route as AuthenticatedAkademikTahunAjaranRouteImport } from './routes/_authenticated/akademik/tahun-ajaran'
import { Route as AuthenticatedAkademikSiswaRouteImport } from './routes/_authenticated/akademik/siswa'
import { Route as AuthenticatedAkademikPresensiRouteImport } from './routes/_authenticated/akademik/presensi'
import { Route as AuthenticatedAkademikNilaiRouteImport } from './routes/_authenticated/akademik/nilai'
import { Route as AuthenticatedAkademikMataPelajaranRouteImport } from './routes/_authenticated/akademik/mata-pelajaran'
import { Route as AuthenticatedAkademikKelasRouteImport } from './routes/_authenticated/akademik/kelas'
import { Route as AuthenticatedAkademikJadwalRouteImport } from './routes/_authenticated/akademik/jadwal'
import { Route as AuthenticatedAkademikImporRouteImport } from './routes/_authenticated/akademik/impor'
import { Route as AuthenticatedAkademikGuruRouteImport } from './routes/_authenticated/akademik/guru'
import { Route as AuthenticatedAkademikCetakNilaiRouteImport } from './routes/_authenticated/akademik/cetak-nilai'

const OpgRoute = OpgRouteImport.update({
  id: '/opg',
  path: '/opg',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSistemSekolahRoute =
  AuthenticatedSistemSekolahRouteImport.update({
    id: '/sistem/sekolah',
    path: '/sistem/sekolah',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemPenggunaRoute =
  AuthenticatedSistemPenggunaRouteImport.update({
    id: '/sistem/pengguna',
    path: '/sistem/pengguna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemPengaturanRoute =
  AuthenticatedSistemPengaturanRouteImport.update({
    id: '/sistem/pengaturan',
    path: '/sistem/pengaturan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemAuditRoute =
  AuthenticatedSistemAuditRouteImport.update({
    id: '/sistem/audit',
    path: '/sistem/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganTagihanRoute =
  AuthenticatedKeuanganTagihanRouteImport.update({
    id: '/keuangan/tagihan',
    path: '/keuangan/tagihan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganPembayaranRoute =
  AuthenticatedKeuanganPembayaranRouteImport.update({
    id: '/keuangan/pembayaran',
    path: '/keuangan/pembayaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganKasBankRoute =
  AuthenticatedKeuanganKasBankRouteImport.update({
    id: '/keuangan/kas-bank',
    path: '/keuangan/kas-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganCekPeriodeRoute =
  AuthenticatedKeuanganCekPeriodeRouteImport.update({
    id: '/keuangan/cek-periode',
    path: '/keuangan/cek-periode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkuntansiLaporanRoute =
  AuthenticatedAkuntansiLaporanRouteImport.update({
    id: '/akuntansi/laporan',
    path: '/akuntansi/laporan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkuntansiJurnalRoute =
  AuthenticatedAkuntansiJurnalRouteImport.update({
    id: '/akuntansi/jurnal',
    path: '/akuntansi/jurnal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikTahunAjaranRoute =
  AuthenticatedAkademikTahunAjaranRouteImport.update({
    id: '/akademik/tahun-ajaran',
    path: '/akademik/tahun-ajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikSiswaRoute =
  AuthenticatedAkademikSiswaRouteImport.update({
    id: '/akademik/siswa',
    path: '/akademik/siswa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikPresensiRoute =
  AuthenticatedAkademikPresensiRouteImport.update({
    id: '/akademik/presensi',
    path: '/akademik/presensi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikNilaiRoute =
  AuthenticatedAkademikNilaiRouteImport.update({
    id: '/akademik/nilai',
    path: '/akademik/nilai',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikMataPelajaranRoute =
  AuthenticatedAkademikMataPelajaranRouteImport.update({
    id: '/akademik/mata-pelajaran',
    path: '/akademik/mata-pelajaran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikKelasRoute =
  AuthenticatedAkademikKelasRouteImport.update({
    id: '/akademik/kelas',
    path: '/akademik/kelas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikJadwalRoute =
  AuthenticatedAkademikJadwalRouteImport.update({
    id: '/akademik/jadwal',
    path: '/akademik/jadwal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikImporRoute =
  AuthenticatedAkademikImporRouteImport.update({
    id: '/akademik/impor',
    path: '/akademik/impor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikGuruRoute =
  AuthenticatedAkademikGuruRouteImport.update({
    id: '/akademik/guru',
    path: '/akademik/guru',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkademikCetakNilaiRoute =
  AuthenticatedAkademikCetakNilaiRouteImport.update({
    id: '/akademik/cetak-nilai',
    path: '/akademik/cetak-nilai',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/opg': typeof OpgRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/akademik/cetak-nilai': typeof AuthenticatedAkademikCetakNilaiRoute
  '/akademik/guru': typeof AuthenticatedAkademikGuruRoute
  '/akademik/impor': typeof AuthenticatedAkademikImporRoute
  '/akademik/jadwal': typeof AuthenticatedAkademikJadwalRoute
  '/akademik/kelas': typeof AuthenticatedAkademikKelasRoute
  '/akademik/mata-pelajaran': typeof AuthenticatedAkademikMataPelajaranRoute
  '/akademik/nilai': typeof AuthenticatedAkademikNilaiRoute
  '/akademik/presensi': typeof AuthenticatedAkademikPresensiRoute
  '/akademik/siswa': typeof AuthenticatedAkademikSiswaRoute
  '/akademik/tahun-ajaran': typeof AuthenticatedAkademikTahunAjaranRoute
  '/akuntansi/jurnal': typeof AuthenticatedAkuntansiJurnalRoute
  '/akuntansi/laporan': typeof AuthenticatedAkuntansiLaporanRoute
  '/keuangan/cek-periode': typeof AuthenticatedKeuanganCekPeriodeRoute
  '/keuangan/kas-bank': typeof AuthenticatedKeuanganKasBankRoute
  '/keuangan/pembayaran': typeof AuthenticatedKeuanganPembayaranRoute
  '/keuangan/tagihan': typeof AuthenticatedKeuanganTagihanRoute
  '/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/opg': typeof OpgRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/akademik/cetak-nilai': typeof AuthenticatedAkademikCetakNilaiRoute
  '/akademik/guru': typeof AuthenticatedAkademikGuruRoute
  '/akademik/impor': typeof AuthenticatedAkademikImporRoute
  '/akademik/jadwal': typeof AuthenticatedAkademikJadwalRoute
  '/akademik/kelas': typeof AuthenticatedAkademikKelasRoute
  '/akademik/mata-pelajaran': typeof AuthenticatedAkademikMataPelajaranRoute
  '/akademik/nilai': typeof AuthenticatedAkademikNilaiRoute
  '/akademik/presensi': typeof AuthenticatedAkademikPresensiRoute
  '/akademik/siswa': typeof AuthenticatedAkademikSiswaRoute
  '/akademik/tahun-ajaran': typeof AuthenticatedAkademikTahunAjaranRoute
  '/akuntansi/jurnal': typeof AuthenticatedAkuntansiJurnalRoute
  '/akuntansi/laporan': typeof AuthenticatedAkuntansiLaporanRoute
  '/keuangan/cek-periode': typeof AuthenticatedKeuanganCekPeriodeRoute
  '/keuangan/kas-bank': typeof AuthenticatedKeuanganKasBankRoute
  '/keuangan/pembayaran': typeof AuthenticatedKeuanganPembayaranRoute
  '/keuangan/tagihan': typeof AuthenticatedKeuanganTagihanRoute
  '/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/opg': typeof OpgRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/akademik/cetak-nilai': typeof AuthenticatedAkademikCetakNilaiRoute
  '/_authenticated/akademik/guru': typeof AuthenticatedAkademikGuruRoute
  '/_authenticated/akademik/impor': typeof AuthenticatedAkademikImporRoute
  '/_authenticated/akademik/jadwal': typeof AuthenticatedAkademikJadwalRoute
  '/_authenticated/akademik/kelas': typeof AuthenticatedAkademikKelasRoute
  '/_authenticated/akademik/mata-pelajaran': typeof AuthenticatedAkademikMataPelajaranRoute
  '/_authenticated/akademik/nilai': typeof AuthenticatedAkademikNilaiRoute
  '/_authenticated/akademik/presensi': typeof AuthenticatedAkademikPresensiRoute
  '/_authenticated/akademik/siswa': typeof AuthenticatedAkademikSiswaRoute
  '/_authenticated/akademik/tahun-ajaran': typeof AuthenticatedAkademikTahunAjaranRoute
  '/_authenticated/akuntansi/jurnal': typeof AuthenticatedAkuntansiJurnalRoute
  '/_authenticated/akuntansi/laporan': typeof AuthenticatedAkuntansiLaporanRoute
  '/_authenticated/keuangan/cek-periode': typeof AuthenticatedKeuanganCekPeriodeRoute
  '/_authenticated/keuangan/kas-bank': typeof AuthenticatedKeuanganKasBankRoute
  '/_authenticated/keuangan/pembayaran': typeof AuthenticatedKeuanganPembayaranRoute
  '/_authenticated/keuangan/tagihan': typeof AuthenticatedKeuanganTagihanRoute
  '/_authenticated/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/_authenticated/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/_authenticated/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/_authenticated/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/opg'
    | '/dashboard'
    | '/setup'
    | '/akademik/cetak-nilai'
    | '/akademik/guru'
    | '/akademik/impor'
    | '/akademik/jadwal'
    | '/akademik/kelas'
    | '/akademik/mata-pelajaran'
    | '/akademik/nilai'
    | '/akademik/presensi'
    | '/akademik/siswa'
    | '/akademik/tahun-ajaran'
    | '/akuntansi/jurnal'
    | '/akuntansi/laporan'
    | '/keuangan/cek-periode'
    | '/keuangan/kas-bank'
    | '/keuangan/pembayaran'
    | '/keuangan/tagihan'
    | '/sistem/audit'
    | '/sistem/pengaturan'
    | '/sistem/pengguna'
    | '/sistem/sekolah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/opg'
    | '/dashboard'
    | '/setup'
    | '/akademik/cetak-nilai'
    | '/akademik/guru'
    | '/akademik/impor'
    | '/akademik/jadwal'
    | '/akademik/kelas'
    | '/akademik/mata-pelajaran'
    | '/akademik/nilai'
    | '/akademik/presensi'
    | '/akademik/siswa'
    | '/akademik/tahun-ajaran'
    | '/akuntansi/jurnal'
    | '/akuntansi/laporan'
    | '/keuangan/cek-periode'
    | '/keuangan/kas-bank'
    | '/keuangan/pembayaran'
    | '/keuangan/tagihan'
    | '/sistem/audit'
    | '/sistem/pengaturan'
    | '/sistem/pengguna'
    | '/sistem/sekolah'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/opg'
    | '/_authenticated/dashboard'
    | '/_authenticated/setup'
    | '/_authenticated/akademik/cetak-nilai'
    | '/_authenticated/akademik/guru'
    | '/_authenticated/akademik/impor'
    | '/_authenticated/akademik/jadwal'
    | '/_authenticated/akademik/kelas'
    | '/_authenticated/akademik/mata-pelajaran'
    | '/_authenticated/akademik/nilai'
    | '/_authenticated/akademik/presensi'
    | '/_authenticated/akademik/siswa'
    | '/_authenticated/akademik/tahun-ajaran'
    | '/_authenticated/akuntansi/jurnal'
    | '/_authenticated/akuntansi/laporan'
    | '/_authenticated/keuangan/cek-periode'
    | '/_authenticated/keuangan/kas-bank'
    | '/_authenticated/keuangan/pembayaran'
    | '/_authenticated/keuangan/tagihan'
    | '/_authenticated/sistem/audit'
    | '/_authenticated/sistem/pengaturan'
    | '/_authenticated/sistem/pengguna'
    | '/_authenticated/sistem/sekolah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OpgRoute: typeof OpgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opg': {
      id: '/opg'
      path: '/opg'
      fullPath: '/opg'
      preLoaderRoute: typeof OpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/sekolah': {
      id: '/_authenticated/sistem/sekolah'
      path: '/sistem/sekolah'
      fullPath: '/sistem/sekolah'
      preLoaderRoute: typeof AuthenticatedSistemSekolahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/pengguna': {
      id: '/_authenticated/sistem/pengguna'
      path: '/sistem/pengguna'
      fullPath: '/sistem/pengguna'
      preLoaderRoute: typeof AuthenticatedSistemPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/pengaturan': {
      id: '/_authenticated/sistem/pengaturan'
      path: '/sistem/pengaturan'
      fullPath: '/sistem/pengaturan'
      preLoaderRoute: typeof AuthenticatedSistemPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/audit': {
      id: '/_authenticated/sistem/audit'
      path: '/sistem/audit'
      fullPath: '/sistem/audit'
      preLoaderRoute: typeof AuthenticatedSistemAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/tagihan': {
      id: '/_authenticated/keuangan/tagihan'
      path: '/keuangan/tagihan'
      fullPath: '/keuangan/tagihan'
      preLoaderRoute: typeof AuthenticatedKeuanganTagihanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/pembayaran': {
      id: '/_authenticated/keuangan/pembayaran'
      path: '/keuangan/pembayaran'
      fullPath: '/keuangan/pembayaran'
      preLoaderRoute: typeof AuthenticatedKeuanganPembayaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/kas-bank': {
      id: '/_authenticated/keuangan/kas-bank'
      path: '/keuangan/kas-bank'
      fullPath: '/keuangan/kas-bank'
      preLoaderRoute: typeof AuthenticatedKeuanganKasBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/cek-periode': {
      id: '/_authenticated/keuangan/cek-periode'
      path: '/keuangan/cek-periode'
      fullPath: '/keuangan/cek-periode'
      preLoaderRoute: typeof AuthenticatedKeuanganCekPeriodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akuntansi/laporan': {
      id: '/_authenticated/akuntansi/laporan'
      path: '/akuntansi/laporan'
      fullPath: '/akuntansi/laporan'
      preLoaderRoute: typeof AuthenticatedAkuntansiLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akuntansi/jurnal': {
      id: '/_authenticated/akuntansi/jurnal'
      path: '/akuntansi/jurnal'
      fullPath: '/akuntansi/jurnal'
      preLoaderRoute: typeof AuthenticatedAkuntansiJurnalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/tahun-ajaran': {
      id: '/_authenticated/akademik/tahun-ajaran'
      path: '/akademik/tahun-ajaran'
      fullPath: '/akademik/tahun-ajaran'
      preLoaderRoute: typeof AuthenticatedAkademikTahunAjaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/siswa': {
      id: '/_authenticated/akademik/siswa'
      path: '/akademik/siswa'
      fullPath: '/akademik/siswa'
      preLoaderRoute: typeof AuthenticatedAkademikSiswaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/presensi': {
      id: '/_authenticated/akademik/presensi'
      path: '/akademik/presensi'
      fullPath: '/akademik/presensi'
      preLoaderRoute: typeof AuthenticatedAkademikPresensiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/nilai': {
      id: '/_authenticated/akademik/nilai'
      path: '/akademik/nilai'
      fullPath: '/akademik/nilai'
      preLoaderRoute: typeof AuthenticatedAkademikNilaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/mata-pelajaran': {
      id: '/_authenticated/akademik/mata-pelajaran'
      path: '/akademik/mata-pelajaran'
      fullPath: '/akademik/mata-pelajaran'
      preLoaderRoute: typeof AuthenticatedAkademikMataPelajaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/kelas': {
      id: '/_authenticated/akademik/kelas'
      path: '/akademik/kelas'
      fullPath: '/akademik/kelas'
      preLoaderRoute: typeof AuthenticatedAkademikKelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/jadwal': {
      id: '/_authenticated/akademik/jadwal'
      path: '/akademik/jadwal'
      fullPath: '/akademik/jadwal'
      preLoaderRoute: typeof AuthenticatedAkademikJadwalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/impor': {
      id: '/_authenticated/akademik/impor'
      path: '/akademik/impor'
      fullPath: '/akademik/impor'
      preLoaderRoute: typeof AuthenticatedAkademikImporRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/guru': {
      id: '/_authenticated/akademik/guru'
      path: '/akademik/guru'
      fullPath: '/akademik/guru'
      preLoaderRoute: typeof AuthenticatedAkademikGuruRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akademik/cetak-nilai': {
      id: '/_authenticated/akademik/cetak-nilai'
      path: '/akademik/cetak-nilai'
      fullPath: '/akademik/cetak-nilai'
      preLoaderRoute: typeof AuthenticatedAkademikCetakNilaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedAkademikCetakNilaiRoute: typeof AuthenticatedAkademikCetakNilaiRoute
  AuthenticatedAkademikGuruRoute: typeof AuthenticatedAkademikGuruRoute
  AuthenticatedAkademikImporRoute: typeof AuthenticatedAkademikImporRoute
  AuthenticatedAkademikJadwalRoute: typeof AuthenticatedAkademikJadwalRoute
  AuthenticatedAkademikKelasRoute: typeof AuthenticatedAkademikKelasRoute
  AuthenticatedAkademikMataPelajaranRoute: typeof AuthenticatedAkademikMataPelajaranRoute
  AuthenticatedAkademikNilaiRoute: typeof AuthenticatedAkademikNilaiRoute
  AuthenticatedAkademikPresensiRoute: typeof AuthenticatedAkademikPresensiRoute
  AuthenticatedAkademikSiswaRoute: typeof AuthenticatedAkademikSiswaRoute
  AuthenticatedAkademikTahunAjaranRoute: typeof AuthenticatedAkademikTahunAjaranRoute
  AuthenticatedAkuntansiJurnalRoute: typeof AuthenticatedAkuntansiJurnalRoute
  AuthenticatedAkuntansiLaporanRoute: typeof AuthenticatedAkuntansiLaporanRoute
  AuthenticatedKeuanganCekPeriodeRoute: typeof AuthenticatedKeuanganCekPeriodeRoute
  AuthenticatedKeuanganKasBankRoute: typeof AuthenticatedKeuanganKasBankRoute
  AuthenticatedKeuanganPembayaranRoute: typeof AuthenticatedKeuanganPembayaranRoute
  AuthenticatedKeuanganTagihanRoute: typeof AuthenticatedKeuanganTagihanRoute
  AuthenticatedSistemAuditRoute: typeof AuthenticatedSistemAuditRoute
  AuthenticatedSistemPengaturanRoute: typeof AuthenticatedSistemPengaturanRoute
  AuthenticatedSistemPenggunaRoute: typeof AuthenticatedSistemPenggunaRoute
  AuthenticatedSistemSekolahRoute: typeof AuthenticatedSistemSekolahRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedAkademikCetakNilaiRoute: AuthenticatedAkademikCetakNilaiRoute,
  AuthenticatedAkademikGuruRoute: AuthenticatedAkademikGuruRoute,
  AuthenticatedAkademikImporRoute: AuthenticatedAkademikImporRoute,
  AuthenticatedAkademikJadwalRoute: AuthenticatedAkademikJadwalRoute,
  AuthenticatedAkademikKelasRoute: AuthenticatedAkademikKelasRoute,
  AuthenticatedAkademikMataPelajaranRoute:
    AuthenticatedAkademikMataPelajaranRoute,
  AuthenticatedAkademikNilaiRoute: AuthenticatedAkademikNilaiRoute,
  AuthenticatedAkademikPresensiRoute: AuthenticatedAkademikPresensiRoute,
  AuthenticatedAkademikSiswaRoute: AuthenticatedAkademikSiswaRoute,
  AuthenticatedAkademikTahunAjaranRoute: AuthenticatedAkademikTahunAjaranRoute,
  AuthenticatedAkuntansiJurnalRoute: AuthenticatedAkuntansiJurnalRoute,
  AuthenticatedAkuntansiLaporanRoute: AuthenticatedAkuntansiLaporanRoute,
  AuthenticatedKeuanganCekPeriodeRoute: AuthenticatedKeuanganCekPeriodeRoute,
  AuthenticatedKeuanganKasBankRoute: AuthenticatedKeuanganKasBankRoute,
  AuthenticatedKeuanganPembayaranRoute: AuthenticatedKeuanganPembayaranRoute,
  AuthenticatedKeuanganTagihanRoute: AuthenticatedKeuanganTagihanRoute,
  AuthenticatedSistemAuditRoute: AuthenticatedSistemAuditRoute,
  AuthenticatedSistemPengaturanRoute: AuthenticatedSistemPengaturanRoute,
  AuthenticatedSistemPenggunaRoute: AuthenticatedSistemPenggunaRoute,
  AuthenticatedSistemSekolahRoute: AuthenticatedSistemSekolahRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OpgRoute: OpgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
